User.create!(email:"root@localhost",password:"admin123", password_confirmation:"admin123")
Customer.create!(name:"T-mobile",zone:1)
Customer.create!(name:"O2",zone:2)
Governings.create!(customer_id:1,user_id:1)
Governings.create!(customer_id:2,user_id:1)